### PR TITLE
✨  Add reference to hd details table

### PR DESCRIPTION
**Pull request by REX-Alexander**
Adds support for a reference to target separate instances of Hd Details Table. A requirement for: [#REAL-4538](https://homeday.atlassian.net/jira/software/c/projects/REAL/boards/7?modal=detail&selectedIssue=REAL-4538) to work.

### CODE REVIEW

**Review by volcanioo — APPROVED** [review]

**Review by aym3nb — APPROVED** [review]

**Comment by leandroinacio** [comment]
I'm a bit without scope, but how exactly does this new prop affect the component?
Could you add a story on storybook to show why we have it and how to use it?
(don't take this as a blocker to merge though)

**Comment by leandroinacio** [comment]
I'm asking because looks like you just want to bind a reference="x" to this component (based on just looking at the code).
Yet, [inheritAttrs](https://vuejs.org/guide/components/attrs.html#disabling-attribute-inheritance) is set to true here, so you could just pass the attribute and it would stick with the component.

And if someone else use this component now (with this change), we'll always have a reference="", increasing our DOM. 
It would be a problem for us at the website project. (although we are not using, I'm just raising this point in case we ever use)

**Review by leandroinacio — APPROVED** [review]

**Comment by REX-Alexander** [comment]
@leandroinacio - I've tried changing things as you suggested in Storybook but it's my first time changing things there so it might all be wrong 😅

**Review by leandroinacio — APPROVED** [review]
@REX-Alexander it's not wrong at all! Looks perfect, you we can check the result here:
https://frontend-pulls.homeday.de/homeday-blocks/1007/?path=/docs/components-hddetailstable--default

At the bottom, in the "Docs" tab we can see your description to the prop.
Nice work, and thank you again for taking care of this legacy doc structure 👏 

And fyi for the other reviewers, he had to keep the prop because createElement does not render attributes that are not listed in the Element interface. But as an optional nullable field, shouldn't affect other places unless the prop is explicitly declared.

**Pull request merged**
