### PR TITLE
👷 Automate the releasing/publishing process

### PR DESCRIPTION
**Pull request by ilyasmez**
### What is this PR about?

This PR should automate our releasing process, so no more manual and error-prone steps. Releasing a new version should be as easy as merging to `master`. The changelog generation and the version bump are being taken care of automatically.

### Packages used
This automation is based on [semantic-release](https://semantic-release.gitbook.io/) and [semantic-release-gitmoji](https://github.com/momocow/semantic-release-gitmoji).

### Semantic gitmojis
Gitmojis are not directly compatible with semantic versioning, that's why I created a simple `semantic-gitmojis.js` that helps us map the gitmojis to the their equivalent version bump (`major`, `minor`, `patch`).

I've already created a [PR](https://github.com/carloscuesta/gitmoji/pull/692) in the Gitmoji repo, to add an official mapping.
When it's merged, I'm going to remove the mapping from our project.

### Example
Screen Shot 2021-02-02 at 1 35 19 PM

### CODE REVIEW

**Review by volcanioo — APPROVED** [review]
Wow! Great work, man! This was the one that what we needed. 🚀

**Review by leandroinacio — APPROVED** [review]
Looks great :)
I wonder though, if we should start documenting the structure of these actions. We have docs for how to create the PRs and bump versions, but as these actions grow and become more complex I think we should have a README just for them to point out each action, their rules (and why of the rules) and what each file does.

**Review by aym3nb — APPROVED** [review]
As usual, great automation man 👏 🎉 🚀

**Comment by ilyasmez** [comment]
> I wonder though, if we should start documenting the structure of these actions. We have docs for how to create the PRs and bump versions, but as these actions grow and become more complex I think we should have a README just for them to point out each action, their rules (and why of the rules) and what each file does.

Hi @leandroinacio, Github workflows are structured in a way that makes them "easy" to follow, you have the name of the workflow (should be descriptive), the trigger condition (when should this workflow be triggered), then the jobs and their steps (and each step should have a descriptive name).

Is there any part of the workflow that you find confusing?
Do you think that it can be fixed with better naming or even with a few comments?

(Documenting is great, don't get me wrong, but over-documenting has its drawbacks as well 😄)

**Comment by ilyasmez** [comment]
I'll merge the PR to test it IRL, please feel free to drop your comments, I'll create followup PRs if needed.

**Pull request merged**
