### PR TITLE
[B] Remove blurred transition of image slide on Gallery

### PR DESCRIPTION
**Pull request by volcanioo**
https://homeday.atlassian.net/browse/CA-2366

### CODE REVIEW

**Comment by volcanioo** [comment]
@ilyasmez We discussed the same ideas with Gregor. I already recommended that but he still wants to remove, let's talk about it together when he back to the office. 

At the same time, the blur effect needs to scale. We shouldn't remove the only scale, the reason for this: 
> I added a style too. Because image element borders did not blur when filter property works. I used the scale feature for the image. In that way, we can hide these unblurred corners when shows.
https://github.com/homeday-de/homeday-blocks/pull/423#issuecomment-622973589

About `transition`, I do agree, I'll update this.

**Comment by ilyasmez** [comment]
I think that the blur is an essential part of the lazy loading.
Currently the sequence looks like this:
`[image 1] -(user clicks next)-> [blurred image 2 thumbnail] -(0.3s fade-out transition)-> [image 2]`
With your changes:
`[image 1] -(user clicks next)-> [pixelized image 2 thumbnail] -(0.3s fade-out transition)-> [image 2]`
For simplification, I excluded the scale animation in the example.

So as you can see it's not making it any better. Maybe the opposite.

If you want the user to have "a quick impression of the property", then I would suggest to decrease the `0.3s` to maybe `0.15s`. But showing them a pixelized photo won't help.

I got the reason behind the scale animation, but it causes an undesirable motion animation, so I'm not sure if the blurred borders are more noticeable. But this one is a trade-off.

**Comment by volcanioo** [comment]
I do agree, I'll talk with Gregor about it and if he accepts that: I'll update the transition time and I'll remove the scale thing. Thank you for your cooperation @ilyasmez.

**Comment by volcanioo** [comment]
I talked with Gregor, We decided to use the blurred effect for now.

**Pull request merged**
