### PR TITLE
:arrow_up: upgrade babel/helper-compilation-targets

### PR DESCRIPTION
**Pull request by drapisarda**
`npm run build:storybook `
fails without this.

The displayed error on the CLI is 
`
No "exports" main resolved in <your project folder>/node_modules/@babel/helper-compilation-targets/package.json
`

### CODE REVIEW

**Review by kuroski — APPROVED** [review]
🚢

**Comment by viniciuskneves** [comment]
Anyone else having this very same issue?

Have you checked Node version if it matches `.nvmrc`?

**Comment by ilyasmez** [comment]
As @viniciuskneves mentioned that should be just a node version incompatibility issue.
Make sure you run:
```bash
nvm use
```
before running `npm i` or `npm run serve:storybook`

**Comment by ilyasmez** [comment]
@drapisarda, if your problem is solved by using the right node version, please close this PR.

**Pull request closed without merging**
